# Generated by Django 5.2.7 on 2025-11-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="tin_number",
            field=models.CharField(
                blank=True, help_text="e.g., 000-000-000-001", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.CharField(
                blank=True, help_text="Full business address", max_length=255
            ),
        ),
    ]
